Shutdown webdirve before parent's teardownClass()
In tearDownClass() function, webdirver should shutdown at
first and then close the display, finally to call parent's
tearDownClass() logic.

By doing this, the follow RuntimeError can be avoid.

ERROR: test suite for <class 'iris.core.tests.test_firefox_login.FirefoxLoginTest'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "site-packages/nose/suite.py", line 227, in run
    self.tearDown()
  File "site-packages/nose/suite.py", line 350, in tearDown
    self.teardownContext(ancestor)
  File "site-packages/nose/suite.py", line 366, in teardownContext
    try_run(context, names)
  File "site-packages/nose/util.py", line 470, in try_run
    return func()
  File "iris/core/tests/test_firefox_login.py", line 41, in tearDownClass
    super(FirefoxLoginTest, cls).tearDownClass()
  File "site-packages/django/test/testcases.py", line 1207, in tearDownClass
    cls._tearDownClassInternal()
  File "site-packages/django/test/testcases.py", line 1197, in _tearDownClassInternal
    cls.server_thread.join()
  File "site-packages/django/test/testcases.py", line 1118, in join
    self.httpd.shutdown()
  File "site-packages/django/test/testcases.py", line 1010, in shutdown
    "Failed to shutdown the live test server in 2 seconds. The "
RuntimeError: Failed to shutdown the live test server in 2 seconds. The server might be stuck or generating a slow response.

Also move parent's setUpClass() to the bottom, since the example
code given by Django's official document puts this line at the
last of setUpClass() function.

Change-Id: I6f68ac29421d32020675db49ede7ad2395ba74fb